### PR TITLE
Added endpoint for meals (updated with description)

### LINKED ISSUE #13: Add endpoint for meals (EPIC #1)
# Backend 1: endpoint for meals

Create a service that will get all of the meals served in a particular dining commons on a particular date

Using the api endpoint described here: https://developer.ucsb.edu/apis/dining/dining-menu

Then build a controller endpoint /api/diningcommons/:date-time/:dining-commons-code the returns this information.

### PR DESCRIPTION
**Pull request by HiDropsy**
Closes: #13 
Create a service that will get all of the meals served in a particular dining commons on a particular date
Works on both dokku and localhost
(Meal refers to breakfast, lunch, dinner....)

https://dining.dokku-15.cs.ucsb.edu/swagger-ui/index.html#/UCSBAPIMenuController/getMeals
image
(a valid diningCommonsCode could be de-la-guerra)

Update: now date has description
image

Update: rename USCBAPIMenu to Meal

Update: change datetime's type from string to localdatetime

Update: add 404 error handling and test

### CODE REVIEW

**Review by haohuant — CHANGES_REQUESTED** [review]
I tried testing the controller but it gave this error:

Screenshot 2024-11-22 140426

**Comment by HiDropsy** [comment]
> I tried testing the controller but it gave this error:
> 
> Screenshot 2024-11-22 140426

Look at the description, it now only accepts input with both date and time.

**Comment by haohuant** [comment]
Ah ok. I checked it again and it works for date time. But I thought originally it was supposed to work with just the date given as well.

**Comment by HiDropsy** [comment]
> Ah ok. I checked it again and it works for date time. But I thought originally it was supposed to work with just the date given as well.

the localdatetime type is supposed to have time, if we need date, date and time, date and time and time zone, then it will need a complex converter or just go back to use string, so I choose to keep it simple.

**Review by haohuant — DISMISSED** [review]
LGTM, working on dokku

**Review by pconrad — DISMISSED** [review]
LGTM

**Comment by pconrad** [comment]
I've re added the FIXME-deploy tag because even though there is a deployment linked, the endpoint added in this PR doesn't seem to working for me there.

image

image

**Comment by pconrad** [comment]
There's a test coverage gap:

image



You need to write a test where you mock the call to call to restTemplate.exchange.  Try these resources:
* https://www.baeldung.com/spring-mock-rest-template
* https://stackoverflow.com/questions/50271164/how-do-i-mock-resttemplate-exchange

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
